### **Step 1:** Find the cholestrol lab type and match it to the encounter. The diagnostic table will tell us the effective date for the completed report, but we need to match which encounter contains a lab completed for cholesterol.

In [2]:
import pandas
import duckdb

connection = duckdb.connect('novellia.duckdb')
connection.execute('''
SELECT
    DISTINCT observation_name
FROM
    stg_observation
WHERE
    category = 'laboratory'
    AND LOWER(observation_name) LIKE '%chol%'
''').df()

                                    observation_name
0       Cholesterol [Mass/volume] in Serum or Plasma
1                Low Density Lipoprotein Cholesterol
2  Cholesterol in HDL [Mass/volume] in Serum or P...

In [5]:
import pandas
import duckdb

connection = duckdb.connect('novellia.duckdb')
connection.execute('''
SELECT
    *
FROM
    stg_diagnosticreport
''').df()

,diagnostic_report_id,status,report_name,report_code,report_code_system,patient_id,encounter_id,effective_date_time,issued,performer
0,000010da-ddbf-f134-9e23-ff11e5a99656,final,None,34117-2,http://loinc.org,7a57ff65-7378-1ac9-be86-7e12f51f94e3,a98b29b0-f9d5-1c1a-0109-cb17e128994c,2021-10-31T15:14:15-04:00,2021-10-31T15:14:15.258-04:00,Dr. Sancho742 Pérez790
1,0000492b-baa5-c467-aaa1-d5c5d8504fea,final,CBC panel - Blood by Automated count,58410-2,http://loinc.org,c7c5c028-f1fb-962b-8db2-dfd4c6d6b02a,969c91ac-c3a7-8940-56c7-5b87c8f3aa0f,2022-06-10T19:33:30-04:00,2022-06-10T19:33:30.023-04:00,GRACEMED HEALTH CLINIC INC
2,000052d6-0c00-572b-20ad-2b1050c8258c,final,Alcohol Use Disorder Identification Test - Con...,72109-2,http://loinc.org,a8fb9909-8833-a4d1-67a4-c6bd5398ca92,9ac36bde-ae72-053e-14bd-dfab61292658,1982-04-19T18:15:05-05:00,1982-04-19T18:15:05.549-05:00,None
3,000062d5-5ee9-9585-7d15-7b23db812059,final,Urinalysis macro (dipstick) panel - Urine,24357-6,http://loinc.org,dda3d07b-ecb4-1aa8-62ac-541027559e11,2b04527b-d707-b265-d00d-577b43cbaf42,1994-08-15T15:12:09-04:00,1994-08-15T15:12:09.623-04:00,ASCENSION VIA CHRISTI HOSPITAL PITTSBURG INC
4,00010cdc-2198-84ed-8d27-9d4eb10ab634,final,Patient Health Questionnaire 2 item (PHQ-2) [R...,55757-9,http://loinc.org,776451bb-0662-cea7-3691-afe5ec755aff,192cab16-5c5e-c35b-f097-33437ffcca79,2022-04-27T01:36:54-04:00,2022-04-27T01:36:54.142-04:00,None
...,...,...,...,...,...,...,...,...,...,...
160344,fffe4b58-8f7b-ec15-253f-ca46b7452ed6,final,None,34117-2,http://loinc.org,4a326793-814f-5274-8c12-22b85873b2e6,80fce9ca-78fa-dda9-8457-5dfd1adab7bd,2005-12-05T04:07:53-05:00,2005-12-05T04:07:53.829-05:00,Dr. Ronald408 Emard19
160345,fffe7aec-a0b0-6538-a27d-219269c82073,final,Urinalysis macro (dipstick) panel - Urine,24357-6,http://loinc.org,e3cb004a-0888-6270-0dcb-90b1ef9eae0a,3041be97-1124-c20c-890b-8396e67c935a,2018-04-15T21:56:27-04:00,2018-04-15T21:56:27.914-04:00,WESLEY MEDICAL CENTER
160346,ffff031a-590e-6f0a-7963-1a7b8a048147,final,None,34117-2,http://loinc.org,c3375230-4466-aa3b-8e33-4a8dd87a53b9,7fd19fc5-2c2a-d5a7-ffd1-c4fedfea73b8,2023-02-24T07:23:47-05:00,2023-02-24T07:23:47.509-05:00,Dr. Adan632 Hilpert278
160347,ffff1dcf-c1ee-8f79-7196-9a84888e9f91,final,Patient Health Questionnaire 2 item (PHQ-2) [R...,55757-9,http://loinc.org,e4e994c7-c1df-9821-e664-f4e36b90709b,50af6f12-e615-cd6b-9135-d7370c0b1520,2002-11-05T05:30:27-05:00,2002-11-05T05:30:27.419-05:00,None
160348,ffffea7e-8154-bbcf-a69a-b03565979327,final,None,34117-2,http://loinc.org,1c498b42-61fd-6341-69c3-053f6e4fe404,606a27d0-9c17-b199-fead-0f9d2c8d9313,1963-02-22T22:23:09-05:00,1963-02-22T22:23:09.623-05:00,Dr. Jorge Luis88 Quintero729

### **Step 2:** JOIN diagnostic to observation so that I can find the correct / latest report data for completed cholestrol lab per patient. Find all cholesterol labs per patient done, but only pick the most recently completed one.

In [ ]:
connection.execute('''
SELECT
    DISTINCT patient_id,
    diagnostic_report_id,
    report_name,
    report_code
FROM
    stg_diagnosticreport
LEFT JOIN
    
''').df()

,patient_id,diagnostic_report_id,report_name,report_code
0,ea917783-35fe-2a7c-5c76-c0cfd7ea66c8,c4587a9c-6e64-11fe-1ce1-9a1933326166,None,34117-2
1,ba009875-a745-06e3-f2a0-5c9295d39482,c45b8e52-999e-49d1-a022-7520dffc9e08,Alcohol Use Disorder Identification Test - Con...,72109-2
2,8877ef1f-7cd7-3242-d7f0-73cf3f7165f4,c45e2aad-024b-89b5-ce63-60abb9805ca3,Generalized anxiety disorder 7 item (GAD-7),69737-5
3,26a3984f-b2a8-e67f-7abc-ff147a0e6e35,c462eae3-3e87-42bc-959e-1cbb5559508d,Urinalysis macro (dipstick) panel - Urine,24357-6
4,7bf52d54-0d2a-265a-15aa-eeed7aaf4af6,c469f17f-b216-2a45-5197-7a62a087f841,None,34117-2
...,...,...,...,...
160344,3bbb0097-5bb8-899f-f9f3-4123c4ce453b,c44ae26b-3297-bdb7-28e8-a7945c521121,None,34117-2
160345,def49d57-ced7-8e38-b3b3-cc6e60ecb0a5,c44d7af7-660c-29cc-c082-571c0ade1e48,Patient Health Questionnaire 2 item (PHQ-2) [R...,55757-9
160346,3c71cd7c-3a19-46c5-8df4-55425c243b9a,c44f0c67-1c13-a8e3-3a40-332ffd330097,None,34117-2
160347,a332808a-fd6e-5961-82e8-985a7a63e552,c4556b49-5ec5-97d0-a2c4-f95f069f2345,None,34117-2
160348,a5bc08ea-9462-c4f5-1bd2-ff342598ac99,c457eab3-8f81-1f94-9a3b-f369c2adf258,Alcohol Use Disorder Identification Test - Con...,72109-2