In [2]:
import pandas
import duckdb

connection = duckdb.connect('novellia.duckdb')
connection.execute("SHOW TABLES").df()

                    name
0     allergyintolerance
1              condition
2                 device
3       diagnosticreport
4      documentreference
5              encounter
6           immunization
7               location
8      medicationrequest
9            observation
10          organization
11               patient
12          practitioner
13      practitionerrole
14             procedure
15  stg_diagnosticreport
16      stg_immunization
17       stg_observation
18           stg_patient

In [3]:
connection.execute('''
SELECT
    *
FROM
    stg_patient
''').df()

,patient_id,gender,birth_date,last_name,first_name,prefix,address_line,city,state,postal_code,country,marital_status,language,multiple_birth,deceased_date_time
0,001ea705-d3ba-5329-0b27-a7fbde2f4007,male,1943-03-17,Goldner995,Andrew29,Mr.,847 Tremblay Crossroad,Bloom,KS,00000,US,Married,Russian (Russia),False,None
1,006cce35-a7c1-71fc-e4e5-4ecc77920e61,male,1983-08-10,Bailey598,Micheal721,Mr.,317 Towne Extension Apt 37,Ulysses,KS,67880,US,Never Married,English (United States),False,None
2,008dd9b2-f541-d09f-1f67-cd741ece2254,female,1925-06-26,Koch169,Herminia75,Mrs.,987 Skiles Union,Walnut,KS,66780,US,Married,English (United States),False,1978-01-01T16:42:19-05:00
3,00b7a058-8387-0c75-da63-7782ed4cc801,male,2013-11-11,Russel238,Milton509,None,686 Cremin Frontage road,Pittsburg,KS,66762,US,Never Married,English (United States),False,None
4,01004e47-23a4-35a8-d62c-5d9f685986b1,female,1948-11-17,Fahey393,Hilary419,Ms.,265 Hirthe Common Unit 66,Bel Aire,KS,67226,US,Never Married,English (United States),False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1139,fe9dae46-cd75-08a3-e516-b318157a1045,male,1916-01-27,Zemlak964,Santos184,Mr.,546 DuBuque Pathway Apt 41,Spring Hill,KS,66083,US,Married,English (United States),<NA>,1981-08-14T14:54:36-04:00
1140,fed27b28-8c8b-7937-db42-b3b9b16f0a47,male,2006-11-10,Feeney44,Waldo53,None,332 Sipes Approach Unit 61,Derby,KS,67037,US,Never Married,Vietnamese,False,None
1141,ff012ec1-1a5a-24d2-5008-8599e704b658,male,1956-01-26,Wilkinson796,Shawn523,Mr.,897 Bailey Trace,Kansas City,KS,66112,US,Married,English (United States),False,None
1142,ff14eb52-b973-e1f4-86d4-65adc19ce4d6,male,2021-03-29,Christiansen251,Rusty501,None,579 Gislason Avenue Suite 93,Kickapoo,KS,00000,US,Never Married,English (United States),False,None
1143,ffe39562-f998-2ae1-3ec6-7d943c0eb50b,female,2023-01-15,Gaylord332,Emmaline88,None,1002 Collins Park Suite 52,Greensburg,KS,67054,US,Never Married,English (United States),False,None

In [4]:
connection.execute('''
SELECT
    *
FROM
    stg_observation
''').df()

,observation_id,status,category,observation_name,observation_code,observation_code_system,patient_id,encounter_id,effective_date_time,issued,value_quantity,value_unit,value_codeable_concept,value_string
0,0000019b-1ad3-f95b-90f7-7162d4dfb4bd,final,laboratory,Ketones [Presence] in Urine by Test strip,2514-8,http://loinc.org,4109755f-085a-5908-abdf-168596406e33,2d937df2-28e2-0521-f970-8ae48dbfc995,1985-02-13T02:50:00-05:00,1985-02-13T02:50:00.783-05:00,NaN,None,Urine ketone test = +++ (finding),None
1,00000c76-af56-c3c3-972a-8d3a2b4723e1,final,laboratory,"Carbon dioxide, total [Moles/volume] in Blood",20565-8,http://loinc.org,93b485d5-921c-f94c-526e-99a615416965,4d806e90-2e17-6a09-be1e-cda5eda5612b,2015-02-27T14:43:29-05:00,2015-02-27T14:43:29.368-05:00,26.520,mmol/L,None,None
2,00001a82-0312-fe4c-7391-b5cac9f2007c,final,vital-signs,Body Height,8302-2,http://loinc.org,e33cbac7-06e7-425a-e3b5-c23db2d8e9ff,de69024c-0fc1-2990-3c67-1734bcbec5dd,2015-08-01T10:34:35-04:00,2015-08-01T10:34:35.060-04:00,67.100,cm,None,None
3,0000241b-2c9e-389c-1b3a-08afeca79fbf,final,laboratory,Aspartate aminotransferase [Enzymatic activity...,1920-8,http://loinc.org,ad239efc-637c-e428-c829-b87e700d5446,6e74946d-8ed9-466f-6739-5802f2260848,2018-03-15T11:47:06-04:00,2018-03-15T11:47:06.955-04:00,37.191,U/L,None,None
4,00004e10-6835-8173-f786-42aef417abaa,final,laboratory,Potassium [Moles/volume] in Blood,6298-4,http://loinc.org,d8f56f83-4f2a-0133-8335-e053343e5766,0294d1a2-254b-5a6f-77b0-a6bcfe21e5e3,2004-01-09T13:36:59-05:00,2004-01-09T13:36:59.676-05:00,4.980,mmol/L,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693518,ffffa437-9c20-0d27-a09b-12eec3eed39f,final,laboratory,Color of Urine,5778-6,http://loinc.org,9357bf54-856c-2858-8a79-df6e00ff31bc,10582222-fd67-e5db-36f6-cfcc612e150a,2002-04-27T23:59:51-04:00,2002-04-27T23:59:51.812-04:00,NaN,None,Brown color (qualifier value),None
693519,ffffcb6a-2b7f-1503-ada9-fff16ba523f4,final,laboratory,"Carbon dioxide, total [Moles/volume] in Blood",20565-8,http://loinc.org,7d9aa431-cd72-8aa2-9559-5920937d9330,f36c1700-b072-3439-737e-41dc4a12193d,2005-11-24T07:05:37-05:00,2005-11-24T07:05:37.085-05:00,25.240,mmol/L,None,None
693520,ffffdcbb-5f60-c630-98d3-37fe21cff3de,final,vital-signs,Heart rate,8867-4,http://loinc.org,ac91b90d-97e4-4fc5-41cd-036bac49e6e8,85daa6fc-1471-931f-fa1d-05774ce26832,2016-06-25T02:21:46-04:00,2016-06-25T02:21:46.792-04:00,68.000,/min,None,None
693521,ffffe7d8-2356-a197-7762-737d1a6bbce1,final,laboratory,Chloride [Moles/volume] in Serum or Plasma,2075-0,http://loinc.org,ad239efc-637c-e428-c829-b87e700d5446,6373f310-7ca7-1871-9158-75d86b4b62c3,2013-10-18T12:35:06-04:00,2013-10-18T12:35:06.955-04:00,108.390,mmol/L,None,None
693522,fffff018-b138-9634-6e0f-7304d8b5cd2a,final,vital-signs,Body Weight,29463-7,http://loinc.org,94c1cb7d-cd8d-b615-ca96-78b31505fadc,86b08e29-b0fb-5ced-0554-bad22fb96b5e,2020-05-14T00:09:57-04:00,2020-05-14T00:09:57.599-04:00,79.700,kg,None,None

In [5]:
connection.execute('''
SELECT
    *
FROM
    stg_immunization
''').df()

,immunization_id,status,vaccine_name,vaccine_code,vaccine_code_system,patient_id,encounter_id,occurrence_date_time,primary_source,location
0,0000e3ef-3cf9-572b-f476-6398236b3624,completed,"rotavirus, monovalent",119,http://hl7.org/fhir/sid/cvx,8fb4ba44-2680-3ba1-bd88-d1b3dc36746e,952db305-85b8-55bd-2a71-c46270adb226,2020-05-16T05:15:06-04:00,True,"ROCK RIDGE FAMILY MEDICINE, P.A."
1,000a7057-ecc3-0b40-e99f-17aa1a3f344a,completed,"Influenza, seasonal, injectable, preservative ...",140,http://hl7.org/fhir/sid/cvx,57980abf-174f-e0ae-86f9-60000b4ea5e5,4d108fc2-945b-d475-0f1b-4aa1cb49d8a9,2017-02-12T00:02:43-05:00,True,SWOPE HEALTH SERVICES
2,0010398a-13e1-366a-b7f1-d05ff44b64d2,completed,Hib (PRP-OMP),49,http://hl7.org/fhir/sid/cvx,b18064b3-80f0-dbd6-3f27-969d50b31936,0cb9f3eb-b80a-abdd-f849-67dc7b2bf347,2019-05-25T16:45:10-04:00,True,RESTORATION HEALTH CARE LLC
3,00159ce1-b151-d88d-1151-6b741e011255,completed,"Influenza, seasonal, injectable, preservative ...",140,http://hl7.org/fhir/sid/cvx,aee9e860-9323-3451-2e55-9afc1f09ed82,909f30a8-d009-9c20-4797-68b4e7488076,2021-12-26T14:52:05-05:00,True,ELLSWORTH COUNTY MEDICAL CENTER
4,00194103-776e-f6d8-104e-36e9c7ad6876,completed,"Hep A, adult",52,http://hl7.org/fhir/sid/cvx,cb919cb1-f9de-ba69-bb5e-a5bb098ad5c7,9eb1a58c-6a8e-4475-5ace-cc9b9fd95edf,2021-03-25T18:54:26-04:00,True,TRUSTED PRIMARY CARE
...,...,...,...,...,...,...,...,...,...,...
17361,fff85bda-5628-5fd7-2070-64139d5f5237,completed,"Influenza, seasonal, injectable, preservative ...",140,http://hl7.org/fhir/sid/cvx,3972692e-4dd9-7be8-ccef-92258fc199cc,122ea1c4-d184-e748-edaf-ceccf47144a3,2019-02-08T07:20:37-05:00,True,LINCOLN COUNTY MEDICAL CLINIC
17362,fffaa27d-5bc9-0383-3b48-4047883f10d2,completed,"HPV, quadrivalent",62,http://hl7.org/fhir/sid/cvx,9b71153d-67cb-9411-37b7-1e8bdf804f28,2d312b11-0035-95d2-a2d5-53587e1500e1,2020-08-13T19:46:50-04:00,True,SMITH INTERNAL MEDICINE PA
17363,fffaee9d-c978-5dfc-d27b-78dbd60db2d2,completed,"Influenza, seasonal, injectable, preservative ...",140,http://hl7.org/fhir/sid/cvx,a9964e41-645e-5f0c-6043-039e4e11fe11,fb2b608a-6f83-6b39-737d-388a1f9fdbe7,2014-06-02T19:13:52-04:00,True,KANSAS MEDICAL CLINIC PA
17364,ffff5eb2-af0e-24e0-f5df-138cc0304abc,completed,"Influenza, seasonal, injectable, preservative ...",140,http://hl7.org/fhir/sid/cvx,5664031d-7165-6981-9a8d-2dd7228c1201,bf011023-342c-bdef-5acd-2fc3b503df78,2021-01-12T21:47:29-05:00,True,FAMILY MEDCENTERS PA
17365,ffff60ff-025b-e4ab-5f3c-a27e30b0ba5b,completed,"HPV, quadrivalent",62,http://hl7.org/fhir/sid/cvx,f5267362-a0b7-f32b-6ccb-902d215a10f6,583f46c7-4903-1443-1b57-51f22408b9eb,2019-09-18T17:57:29-04:00,True,"FAMILY MEDICINE EAST, CHARTERED"

In [6]:
connection.execute('''
SELECT
    *
FROM
    stg_diagnosticreport
''').df()

,diagnostic_report_id,status,report_name,report_code,report_code_system,patient_id,encounter_id,effective_date_time,issued,performer
0,000010da-ddbf-f134-9e23-ff11e5a99656,final,None,34117-2,http://loinc.org,7a57ff65-7378-1ac9-be86-7e12f51f94e3,a98b29b0-f9d5-1c1a-0109-cb17e128994c,2021-10-31T15:14:15-04:00,2021-10-31T15:14:15.258-04:00,Dr. Sancho742 Pérez790
1,0000492b-baa5-c467-aaa1-d5c5d8504fea,final,CBC panel - Blood by Automated count,58410-2,http://loinc.org,c7c5c028-f1fb-962b-8db2-dfd4c6d6b02a,969c91ac-c3a7-8940-56c7-5b87c8f3aa0f,2022-06-10T19:33:30-04:00,2022-06-10T19:33:30.023-04:00,GRACEMED HEALTH CLINIC INC
2,000052d6-0c00-572b-20ad-2b1050c8258c,final,Alcohol Use Disorder Identification Test - Con...,72109-2,http://loinc.org,a8fb9909-8833-a4d1-67a4-c6bd5398ca92,9ac36bde-ae72-053e-14bd-dfab61292658,1982-04-19T18:15:05-05:00,1982-04-19T18:15:05.549-05:00,None
3,000062d5-5ee9-9585-7d15-7b23db812059,final,Urinalysis macro (dipstick) panel - Urine,24357-6,http://loinc.org,dda3d07b-ecb4-1aa8-62ac-541027559e11,2b04527b-d707-b265-d00d-577b43cbaf42,1994-08-15T15:12:09-04:00,1994-08-15T15:12:09.623-04:00,ASCENSION VIA CHRISTI HOSPITAL PITTSBURG INC
4,00010cdc-2198-84ed-8d27-9d4eb10ab634,final,Patient Health Questionnaire 2 item (PHQ-2) [R...,55757-9,http://loinc.org,776451bb-0662-cea7-3691-afe5ec755aff,192cab16-5c5e-c35b-f097-33437ffcca79,2022-04-27T01:36:54-04:00,2022-04-27T01:36:54.142-04:00,None
...,...,...,...,...,...,...,...,...,...,...
160344,fffe4b58-8f7b-ec15-253f-ca46b7452ed6,final,None,34117-2,http://loinc.org,4a326793-814f-5274-8c12-22b85873b2e6,80fce9ca-78fa-dda9-8457-5dfd1adab7bd,2005-12-05T04:07:53-05:00,2005-12-05T04:07:53.829-05:00,Dr. Ronald408 Emard19
160345,fffe7aec-a0b0-6538-a27d-219269c82073,final,Urinalysis macro (dipstick) panel - Urine,24357-6,http://loinc.org,e3cb004a-0888-6270-0dcb-90b1ef9eae0a,3041be97-1124-c20c-890b-8396e67c935a,2018-04-15T21:56:27-04:00,2018-04-15T21:56:27.914-04:00,WESLEY MEDICAL CENTER
160346,ffff031a-590e-6f0a-7963-1a7b8a048147,final,None,34117-2,http://loinc.org,c3375230-4466-aa3b-8e33-4a8dd87a53b9,7fd19fc5-2c2a-d5a7-ffd1-c4fedfea73b8,2023-02-24T07:23:47-05:00,2023-02-24T07:23:47.509-05:00,Dr. Adan632 Hilpert278
160347,ffff1dcf-c1ee-8f79-7196-9a84888e9f91,final,Patient Health Questionnaire 2 item (PHQ-2) [R...,55757-9,http://loinc.org,e4e994c7-c1df-9821-e664-f4e36b90709b,50af6f12-e615-cd6b-9135-d7370c0b1520,2002-11-05T05:30:27-05:00,2002-11-05T05:30:27.419-05:00,None
160348,ffffea7e-8154-bbcf-a69a-b03565979327,final,None,34117-2,http://loinc.org,1c498b42-61fd-6341-69c3-053f6e4fe404,606a27d0-9c17-b199-fead-0f9d2c8d9313,1963-02-22T22:23:09-05:00,1963-02-22T22:23:09.623-05:00,Dr. Jorge Luis88 Quintero729