In [5]:
import pandas
import duckdb

connection = duckdb.connect('novellia.duckdb')
connection.execute("SHOW TABLES").df()

                  name
0   allergyintolerance
1            condition
2               device
3     diagnosticreport
4    documentreference
5            encounter
6         immunization
7             location
8    medicationrequest
9          observation
10        organization
11             patient
12        practitioner
13    practitionerrole
14           procedure

In [8]:
connection.execute('''
SELECT
    *
FROM
    patient
''').df()

,resourceType,id,meta,text,extension,identifier,name,telecom,gender,birthDate,address,maritalStatus,multipleBirthBoolean,communication,deceasedDateTime,multipleBirthInteger
0,Patient,001ea705-d3ba-5329-0b27-a7fbde2f4007,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Goldner995', '...","[{'system': 'phone', 'value': '555-806-9773', ...",male,1943-03-17,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
1,Patient,006cce35-a7c1-71fc-e4e5-4ecc77920e61,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Bailey598', 'g...","[{'system': 'phone', 'value': '555-315-8314', ...",male,1983-08-10,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
2,Patient,008dd9b2-f541-d09f-1f67-cd741ece2254,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Koch169', 'giv...","[{'system': 'phone', 'value': '555-162-4456', ...",female,1925-06-26,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,1978-01-01T16:42:19-05:00,<NA>
3,Patient,00b7a058-8387-0c75-da63-7782ed4cc801,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Russel238', 'g...","[{'system': 'phone', 'value': '555-320-8440', ...",male,2013-11-11,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
4,Patient,01004e47-23a4-35a8-d62c-5d9f685986b1,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Fahey393', 'gi...","[{'system': 'phone', 'value': '555-620-7272', ...",female,1948-11-17,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1139,Patient,fe9dae46-cd75-08a3-e516-b318157a1045,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Zemlak964', 'g...","[{'system': 'phone', 'value': '555-753-9335', ...",male,1916-01-27,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,<NA>,[{'language': {'coding': [{'system': 'urn:ietf...,1981-08-14T14:54:36-04:00,2
1140,Patient,fed27b28-8c8b-7937-db42-b3b9b16f0a47,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Feeney44', 'gi...","[{'system': 'phone', 'value': '555-259-7533', ...",male,2006-11-10,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
1141,Patient,ff012ec1-1a5a-24d2-5008-8599e704b658,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Wilkinson796',...","[{'system': 'phone', 'value': '555-608-5243', ...",male,1956-01-26,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
1142,Patient,ff14eb52-b973-e1f4-86d4-65adc19ce4d6,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Christiansen25...","[{'system': 'phone', 'value': '555-187-6636', ...",male,2021-03-29,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>
1143,Patient,ffe39562-f998-2ae1-3ec6-7d943c0eb50b,{'profile': ['http://hl7.org/fhir/us/core/Stru...,"{'status': 'generated', 'div': '<div xmlns=""ht...",[{'url': 'http://hl7.org/fhir/us/core/Structur...,[{'system': 'https://github.com/synthetichealt...,"[{'use': 'official', 'family': 'Gaylord332', '...","[{'system': 'phone', 'value': '555-791-4299', ...",female,2023-01-15,[{'extension': [{'url': 'http://hl7.org/fhir/S...,{'coding': [{'system': 'http://terminology.hl7...,False,[{'language': {'coding': [{'system': 'urn:ietf...,None,<NA>